# Generated by Django 5.2.8 on 2025-11-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_message_forwarded_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='allow_friend_requests',
            field=models.BooleanField(default=True),
        ),
    ]
