# Generated by Django 5.2.8 on 2025-11-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_socialprofile_allow_friend_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='banner_color',
            field=models.CharField(default='purple', max_length=20),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='favorite_game',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
